### ISSUE TITLE
Write VTK  file in each time step

### ISSUE THREAD

**Issue by AI-Pranto** [gridley/HorkerPlusPlus#1]
Is it possible of writing **vtk** files in each time step during running in transient mode, @gridley ?

**Comment by gridley** [comment]
It already does! 😄

**Comment by AI-Pranto** [comment]
I want. Can you kindly change it? I think 
`if (ti%10==0) {
        writeOutput(ti);` it needs to be changed. Am I right?

**Comment by gridley** [comment]
Sure thing! I'll add an option in the settings file for this... Very glad to hear of someone using this code! So far it's just been me as far as I know. So, please share any ideas you have about features and feel free to submit pull requests.

**Comment by gridley** [comment]
Hey @AI-Pranto, I just pushed a commit that adds the feature you were looking for. You can see an example of it in "examples/lra_transient". You can set VTK output every 10 (or whatever number you like) timesteps by putting "set write_vtk_interval 10".

Let me know if there's anything you find confusing about this code. Pretty exciting to see someone using it!
